version: '3.8'

services:
  code-generation-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=Qwen/Qwen1.5-7B-Chat
      - MAX_LENGTH=1024
      - DEVICE=auto
      - PYTHONUNBUFFERED=1
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s

volumes:
  huggingface_cache:
    driver: local 